name: Start EC2 Instances

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::905418073202:role/GitAction-DiegoNorman-pipiline
          aws-region: us-east-1

      - name: Starting EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.configure-aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.configure-aws-credentials.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.configure-aws-credentials.outputs.aws-session-token }}
        run: python start_ec2.py \
          --aws-access-key-id $AWS_ACCESS_KEY_ID \
          --aws-secret-access-key $AWS_SECRET_ACCESS_KEY \
          --aws-session-token $AWS_SESSION_TOKEN
