name: Start EC2 Instances

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::905418073202:role/GitAction-DiegoNorman-pipiline
          aws-region: us-east-1

      - name: Start EC2 Instances
        run: |
          python start_ec2.py
